{"name": "Проверка изменения данных авторизованного пользователя", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "create_user = {'login_pass': [], 'response': <Response [403]>}\n\n    @pytest.fixture\n    def login_user(create_user):\n        payload = {\n>           \"email\": create_user['login_pass'][0],\n            \"password\": create_user['login_pass'][1],\n        }\nE       IndexError: list index out of range\n\ntests\\conftest.py:23: IndexError"}, "start": 1719860991750, "stop": 1719860991750, "uuid": "ab4ba141-fc1f-497f-9850-b4019b87d9b4", "historyId": "fc174c36e9b7c332d4feb05f89833fcb", "testCaseId": "fc174c36e9b7c332d4feb05f89833fcb", "fullName": "tests.test_user_authentication.TestChangingUserData#test_user_changing_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestChangingUserData"}, {"name": "host", "value": "DESKTOP-6FRR489"}, {"name": "thread", "value": "17592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}