{"name": "Проверка авторизации пользователем с неверным паролем", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.test_user_authentication.TestLoginUser object at 0x00000265383CB590>, create_user = {'login_pass': [], 'response': <Response [403]>}\n\n    @allure.title('Проверка авторизации пользователем с неверным паролем')\n    def test_login_user_incorrect_password(self, create_user):\n        payload = {\n>           \"email\":  create_user['login_pass'][0],\n            \"password\": \"error\",\n        }\nE       IndexError: list index out of range\n\ntests\\test_user_authentication.py:60: IndexError"}, "start": 1719861132059, "stop": 1719861132060, "uuid": "0b609a29-d434-4233-a2e8-eaee1b5e861d", "historyId": "b1989d319aef0a9eec9347f59afe5406", "testCaseId": "b1989d319aef0a9eec9347f59afe5406", "fullName": "tests.test_user_authentication.TestLoginUser#test_login_user_incorrect_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-6FRR489"}, {"name": "thread", "value": "11084-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}