{"name": "Проверка получения списка заказов неавторизованным пользователем", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "create_user = {'login_pass': [], 'response': <Response [403]>}\n\n    @pytest.fixture\n    def login_user(create_user):\n        payload = {\n>           \"email\": create_user['login_pass'][0],\n            \"password\": create_user['login_pass'][1],\n        }\nE       IndexError: list index out of range\n\ntests\\conftest.py:23: IndexError"}, "start": 1719861146376, "stop": 1719861146376, "uuid": "da610adf-758b-42e7-b780-774dd46b247d", "historyId": "77b069256690e0f08f86a8a9b6756ce5", "testCaseId": "77b069256690e0f08f86a8a9b6756ce5", "fullName": "tests.test_create_orders.TestReceivingUserOrders#test_receiving_user_orders", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_orders"}, {"name": "subSuite", "value": "TestReceivingUserOrders"}, {"name": "host", "value": "DESKTOP-6FRR489"}, {"name": "thread", "value": "10036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_orders"}]}